<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <Nullable>enable</Nullable>
        <PackageId>RobloxCloud.Client</PackageId>
        <Version>0.0.1-alpha2</Version>
        <Title>A roblox client that accesses Cloud API</Title>
        <Authors>SimobiSirOP</Authors>

        <Copyright>Copyright © SimobiSirOP 2026</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/SimobiSirOP/RobloxCloud.Client</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/SimobiSirOP/RobloxCloud.Client.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>A async API Wrapper to access Roblox Cloud API</Description>
        <PackageTags>roblox;api;server</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AssemblyName>RobloxCloudApi</AssemblyName>
        <RootNamespace>RobloxCloudApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../README.md">
            <Pack>True</Pack>
            <PackagePath>/</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\RobloxCloudApi\ApiTypes\DataStoresApi\Requests\MemoryStore\" />
    </ItemGroup>

</Project>
