# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    env:
      Configuration: Debug
      UnitTestsPath: UnitTests
      PackagePath: bin/Debug
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration $Configuration
      - name: Test
        env:
          ROBLOX_API_TOKEN: ${{ secrets.ROBLOX_API_TOKEN }}
          ROBLOX_UNIVERSE_ID: ${{ secrets.ROBLOX_UNIVERSE_ID }}
        run: dotnet test $UnitTestsPath/UnitTests.csproj --verbosity normal --filter "TestCategory=Complete" --configuration $Configuration
      
      # NUGET PUSH
      - name: Nuget Login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          
    
      - name: Nuget Push
        run: dotnet nuget push $PackagePath/*.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \ --skip-duplicate --source https://api.nuget.org/v3/index.json  